baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Bryan Sebesta'
refLinksErrorLevel = 'WARNING'
# refLinksNotFoundURL = '#'

[menu]
  [[menu.nav]]
    name = "Work"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Articles"
    url = "/Articles/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
