baseURL = 'https://splendid-peony-1aefa6.netlify.app/'
languageCode = 'en-us'
title = 'Bryan Sebesta'

[params]
  microblogUrl = 'https://micro.bryansebesta.net'

[menu]
  [[menu.nav]]
    name = "Work"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Garden"
    url = "/digital-garden/"
    weight = 2
  [[menu.nav]]
    name = "Now"
    url = "/now/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
