baseURL = 'https://splendid-peony-1aefa6.netlify.app/'
languageCode = 'en-us'
title = 'Bryan Sebesta'
refLinksErrorLevel = 'WARNING'
# refLinksNotFoundURL = '#'
#[caches.modules]
#  dir = '/modules/'

[params]
  microblogUrl = 'https://micro.bryansebesta.net'

[menu]
  [[menu.nav]]
    name = "Work"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Articles"
    url = "/Articles/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
